In [1]:
import numpy as np
from torch import nn
import torch

###Реализация функции upsampling

In [2]:
def upsampling(input_tensor, size):

    #нахождение размеров изображения
    N, C, H, W = input_tensor.shape
    new_H, new_W = size

    #расчитываем коэффиценты
    scale_factor_H = new_H / H
    scale_factor_W = new_W / W

    #создаём результирующий вектор
    output_np = np.empty((N, C, new_H, new_W))

    #билинейная повышающая дискретизация для каждого канала и выборки
    for n in range(N):
        for c in range(C):
            for i in range(new_H):
                for j in range(new_W):
                    #находим позицию на выходном тензоре
                    x = (i + 0.5) / scale_factor_H - 0.5
                    y = (j + 0.5) / scale_factor_W - 0.5
                    x0 = int(np.floor(x))
                    x1 = min(x0 + 1, H - 1)
                    y0 = int(np.floor(y))
                    y1 = min(y0 + 1, W - 1)
                    #выполнение билинейной интерполяции
                    output_np[n, c, i, j] = (input_tensor[n, c, x0, y0] * (x1 - x) * (y1 - y) +
                                             input_tensor[n, c, x0, y1] * (x1 - x) * (y - y0) +
                                             input_tensor[n, c, x1, y0] * (x - x0) * (y1 - y) +
                                             input_tensor[n, c, x1, y1] * (x - x0) * (y - y0))

    return torch.from_numpy(output_np)

###Тест 1

In [3]:
input_data = torch.rand(1, 3, 4, 4)
output_size = (1, 1)

#результат использования нашей функции upsampling
our_result1 = upsampling(input_data, output_size)
print("Результат использования нашей функции upsampling в тесте 1:")
print(our_result1)
torch_result1 = torch.nn.functional.upsample(input_data, output_size, mode = 'bilinear')
print("\nРезультат использования функции upsample библиотеки PyTorch в тесте 1:")
print(torch_result1)

Результат использования нашей функции upsampling в тесте 1:
tensor([[[[0.5798]],

         [[0.4095]],

         [[0.2138]]]], dtype=torch.float64)

Результат использования функции upsample библиотеки PyTorch в тесте 1:
tensor([[[[0.5798]],

         [[0.4095]],

         [[0.2138]]]])


/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py:3769: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")


###Тест 2

In [ ]:
input_data = torch.rand(1, 3, 4, 4)
output_size = (1, 1)

#результат использования нашей функции upsampling
our_result2 = upsampling(input_data, output_size)
print("Результат использования нашей функции upsampling в тесте 2:")
print(our_result2)
torch_result2 = torch.nn.functional.upsample(input_data, output_size, mode = 'bilinear')
print("\nРезультат использования функции upsample библиотеки PyTorch в тесте 2:")
print(torch_result2)

Результат использования нашей функции upsampling в тесте 2:
tensor([[[[0.3617]],

         [[0.5210]],

         [[0.6796]]]], dtype=torch.float64)

Результат использования функции upsample библиотеки PyTorch в тесте 2:
tensor([[[[0.3617]],

         [[0.5210]],

         [[0.6796]]]])


/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py:3769: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")


###Тест 3

In [ ]:
input_data = torch.rand(1, 3, 4, 4)
output_size = (1, 1)

#результат использования нашей функции upsampling
our_result3 = upsampling(input_data, output_size)
print("Результат использования нашей функции upsampling в тесте 3:")
print(our_result3)
torch_result3 = torch.nn.functional.upsample(input_data, output_size, mode = 'bilinear')
print("\nРезультат использования функции upsample библиотеки PyTorch в тесте 3:")
print(torch_result3)

Результат использования нашей функции upsampling в тесте 3:
tensor([[[[0.5075]],

         [[0.7285]],

         [[0.6242]]]], dtype=torch.float64)

Результат использования функции upsample библиотеки PyTorch в тесте 3:
tensor([[[[0.5075]],

         [[0.7285]],

         [[0.6242]]]])


/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py:3769: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
